# Conda environment
name: corsika_toy_iacr
channels:
  - default
  - conda-forge
dependencies:
  - matplotlib
  - numpy>=1.15.4
  - pytest
  - pytest-cov
  - pytest-runner
  - scipy
  - setuptools
  - tqdm
  - uproot
